import json

# Dados de exemplo com vários títulos de notícias e suas classificações
dados = [
    	{"title": "Novo parque ecológico inaugurado na cidade", "classification": "good"},
    {"title": "Desmatamento na Amazônia atinge níveis alarmantes", "classification": "bad"},
    {"title": "Estudo mostra avanços na recuperação de áreas degradadas", "classification": "good"},
    {"title": "Poluição do ar atinge níveis críticos na região metropolitana", "classification": "bad"},
    {"title": "Empresa anuncia investimento em energia renovável", "classification": "good"},
    {"title": "Aumento do desemprego preocupa economistas", "classification": "bad"},
    {"title": "Queimadas destroem hectares de floresta na região", "classification": "bad"},
    {"title": "Previsão de fortes chuvas provoca alerta em áreas de risco", "classification": "bad"},
    {"title": "Enchentes deixam comunidades isoladas e causam prejuízos", "classification": "bad"},
    {"title": "Assoreamento de rios ameaça ecossistemas aquáticos", "classification": "bad"},
    {"title": "Barragem apresenta rachaduras e preocupa moradores", "classification": "bad"},
    {"title": "Deslizamentos de terra interditam rodovias em região montanhosa", "classification": "bad"},
    {"title": "Poluição do ar atinge níveis críticos na cidade", "classification": "bad"},
    {"title": "Especialistas alertam para aumento do aquecimento global", "classification": "bad"},
    {"title": "Conferência discute medidas contra mudanças climáticas", "classification": "good"},
    {"title": "Programa de reciclagem reduz impacto ambiental na comunidade", "classification": "good"},
    {"title": "Incêndio florestal ameaça vida selvagem em reserva natural", "classification": "bad"},
    {"title": "Chuvas intensas causam alagamentos em áreas urbanas", "classification": "bad"},
    {"title": "Enchentes recorrentes preocupam moradores de região costeira", "classification": "bad"},
    {"title": "Assoreamento de lagos compromete abastecimento de água", "classification": "bad"},
    {"title": "Rompimento de barragem causa devastação ambiental", "classification": "bad"},
    {"title": "Deslizamento de encosta deixa comunidades isoladas", "classification": "bad"},
    {"title": "Poluição dos oceanos ameaça biodiversidade marinha", "classification": "bad"},
    {"title": "Emissões de gases de efeito estufa atingem novo recorde", "classification": "bad"},
    {"title": "Adoção de energias renováveis reduz impacto ambiental", "classification": "good"},
    {"title": "Cientistas alertam para necessidade de ações urgentes contra mudanças climáticas", "classification": "bad"},
    {"title": "Plano de combate às queimadas é implementado com sucesso", "classification": "good"},
    {"title": "Chuvas regulares trazem alívio para a agricultura", "classification": "good"},
    {"title": "Enchentes são controladas com ações de prevenção", "classification": "good"},
    {"title": "Projeto de revitalização de rios tem resultados positivos", "classification": "good"},
    {"title": "Investimentos em segurança de barragens garantem tranquilidade", "classification": "good"},
    {"title": "Programa de prevenção evita deslizamentos em áreas de risco", "classification": "good"},
    {"title": "Poluição do ar reduz após adoção de medidas ambientais", "classification": "good"},
    {"title": "Iniciativas globais buscam frear o aquecimento global", "classification": "good"},
    {"title": "Comunidades se unem para combater mudanças climáticas", "classification": "good"},
    {"title": "Campanha de conscientização reduz uso de plásticos descartáveis", "classification": "good"},
    {"title": "Incêndios controlados contribuem para renovação de vegetação", "classification": "good"},
    {"title": "Previsão de chuvas traz esperança para regiões afetadas pela seca", "classification": "good"},
    {"title": "Tecnologia ajuda a prever enchentes com maior precisão", "classification": "good"},
    {"title": "Projetos de reflorestamento recuperam áreas degradadas", "classification": "good"},
    {"title": "Barragens são modernizadas visando maior segurança ambiental", "classification": "good"},
    {"title": "Alerta de deslizamentos é emitido com antecedência, evitando tragédias", "classification": "good"},
    {"title": "Redução de emissões de carbono contribui para combater o aquecimento global", "classification": "good"},
    {"title": "Conferência internacional debate soluções para mudanças climáticas", "classification": "good"},
    {"title": "Empresas adotam práticas sustentáveis visando preservação ambiental", "classification": "good"},
    {"title": "Ações locais promovem conscientização sobre impacto da poluição", "classification": "good"},
    {"title": "Queimadas devastam área protegida, causando danos irreparáveis", "classification": "bad"},
    {"title": "Chuvas torrenciais provocam inundações e deixam famílias desabrigadas", "classification": "bad"},
    {"title": "Enchentes recorrentes causam prejuízos milionários a empresas locais", "classification": "bad"},
    {"title": "Assoreamento compromete sistema de abastecimento de água potável", "classification": "bad"},
    {"title": "Barragem se rompe e lança toneladas de rejeitos tóxicos no rio", "classification": "bad"},
    {"title": "Deslizamentos de terra soterram casas em comunidade carente", "classification": "bad"},
    {"title": "Poluição do solo contamina reservatório de água, causando doenças", "classification": "bad"},
    {"title": "Aquecimento global provoca aumento das temperaturas e secas prolongadas", "classification": "bad"},
    {"title": "Mudanças climáticas geram impactos negativos na agricultura local", "classification": "bad"},
    {"title": "Projeto de reflorestamento fracassa devido à falta de recursos", "classification": "bad"},
    {"title": "Incêndio florestal é controlado antes de atingir área habitada", "classification": "good"},
    {"title": "Chuvas regulares revitalizam reservatórios de água", "classification": "good"},
    {"title": "Enchentes são contidas com uso de tecnologias de prevenção", "classification": "good"},
    {"title": "Assoreamento de rios é revertido com programa de revitalização", "classification": "good"},
    {"title": "Barragem recebe manutenção preventiva, garantindo segurança", "classification": "good"},
    {"title": "Deslizamentos são evitados com monitoramento constante do solo", "classification": "good"},
    {"title": "Poluição do ar diminui após implantação de medidas de controle", "classification": "good"},
    {"title": "Aquecimento global é tema de debate global visando soluções", "classification": "good"},
    {"title": "Mudanças climáticas geram oportunidades para inovação sustentável", "classification": "good"},
    {"title": "Conferência internacional adota medidas para combater poluição marinha", "classification": "good"},
    {"title": "Queimadas causam evacuação em massa de comunidades próximas", "classification": "bad"},
    {"title": "Chuvas fortes causam deslizamentos e interrompem rodovias", "classification": "bad"},
    {"title": "Enchentes repentinas deixam rastro de destruição em áreas urbanas", "classification": "bad"},
    {"title": "Assoreamento de rios resulta em escassez de água para consumo", "classification": "bad"},
    {"title": "Barragem apresenta vazamento de produtos químicos nocivos", "classification": "bad"},
    {"title": "Deslizamentos em encostas causam vítimas fatais", "classification": "bad"},
    {"title": "Poluição do ar atinge índices críticos, colocando saúde em risco", "classification": "bad"},
    {"title": "Aquecimento global acelera derretimento de geleiras", "classification": "bad"},
    {"title": "Mudanças climáticas intensificam fenômenos climáticos extremos", "classification": "bad"},
    {"title": "Incêndio em área de preservação destrói habitat de espécies ameaçadas", "classification": "bad"},
    {"title": "Deslizamento de terra deixa comunidade isolada sem acesso a ajuda", "classification": "bad"},
    {"title": "Poluição industrial contamina águas, causando morte de peixes", "classification": "bad"},
    {"title": "Aquecimento global ameaça sobrevivência de animais polar", "classification": "bad"},
    {"title": "Mudanças climáticas afetam safras agrícolas, causando prejuízos", "classification": "bad"},
    {"title": "Desmatamento ilegal destrói ecossistema vital para biodiversidade", "classification": "bad"},
    {"title": "Poluição sonora impacta vida silvestre em áreas naturais", "classification": "bad"},
    {"title": "Aquecimento global aumenta ocorrência de eventos climáticos extremos", "classification": "bad"},
    {"title": "Mudanças climáticas aceleram perda de terras agrícolas para desertificação", "classification": "bad"},
    {"title": "Incêndios florestais consomem vastas áreas de vegetação em minutos", "classification": "bad"},
    {"title": "Deslizamento de terra em área habitada causa destruição de residências", "classification": "bad"},
    {"title": "Queimadas destroem reserva natural e colocam espécies em risco", "classification": "bad"},
    {"title": "Chuvas intensas causam inundações e desabamentos em áreas urbanas", "classification": "bad"},
    {"title": "Enchentes repentinas deixam vítimas e causam danos materiais", "classification": "bad"},
    {"title": "Assoreamento de rio compromete abastecimento de água em cidade", "classification": "bad"},
    {"title": "Barragem se rompe e lança rejeitos tóxicos em ecossistema aquático", "classification": "bad"},
    {"title": "Deslizamentos de terra destroem plantações e afetam agricultores", "classification": "bad"},
    {"title": "Poluição atmosférica atinge níveis alarmantes em área industrial", "classification": "bad"},
    {"title": "Aquecimento global provoca derretimento acelerado de geleiras", "classification": "bad"},
    {"title": "Mudanças climáticas aumentam ocorrência de secas prolongadas", "classification": "bad"},
    {"title": "Incêndio florestal destrói habitat de animais ameaçados de extinção", "classification": "bad"},
    {"title": "Deslizamento de terra bloqueia acesso a comunidades isoladas", "classification": "bad"},
    {"title": "Poluição de rios causa morte em massa de peixes e outros animais aquáticos", "classification": "bad"},
    {"title": "Aquecimento global prejudica reprodução de espécies marinhas", "classification": "bad"},
    {"title": "Mudanças climáticas comprometem produção agrícola e segurança alimentar", "classification": "bad"},
    {"title": "Desmatamento descontrolado causa perda de biodiversidade na floresta", "classification": "bad"},
    {"title": "Poluição sonora afeta saúde mental de animais em habitats naturais", "classification": "bad"},
    {"title": "Aquecimento global leva ao aumento de doenças transmitidas por vetores", "classification": "bad"},
    {"title": "Mudanças climáticas geram conflitos por recursos naturais escassos", "classification": "bad"},
    {"title": "Incêndios florestais destroem áreas de conservação ecológica", "classification": "bad"},
    {"title": "Deslizamento de terra deixa famílias desabrigadas em região montanhosa", "classification": "bad"},
    {"title": "Queimadas impactam qualidade do ar e aumentam casos de doenças respiratórias", "classification": "bad"},
    {"title": "Chuvas torrenciais causam alagamentos e interrompem serviços básicos", "classification": "bad"},
    {"title": "Enchentes repentinas destroem infraestrutura urbana e afetam milhares", "classification": "bad"},
    {"title": "Assoreamento de lago compromete atividades de lazer e pesca", "classification": "bad"},
    {"title": "Barragem em estado precário eleva risco de desastre ambiental", "classification": "bad"},
    {"title": "Deslizamentos de encostas causam vítimas fatais e geram comoção", "classification": "bad"},
    {"title": "Poluição do ar em metrópole ultrapassa limites seguros e afeta saúde pública", "classification": "bad"},
    {"title": "Aquecimento global ameaça extinção de espécies emblemáticas", "classification": "bad"},
    {"title": "Mudanças climáticas causam migrações forçadas e conflitos por território", "classification": "bad"},
    {"title": "Incêndios em áreas de conservação causam perda irreparável de biodiversidade", "classification": "bad"},
    {"title": "Recuperação de área degradada é bem-sucedida e restaura biodiversidade", "classification": "good"},
    {"title": "Projeto de reflorestamento recebe reconhecimento internacional", "classification": "good"},
    {"title": "Campanha de conscientização reduz descarte de plásticos em rios", "classification": "good"},
    {"title": "Criação de áreas protegidas preserva habitats naturais e espécies", "classification": "good"},
    {"title": "Investimentos em energia limpa reduzem emissões de carbono", "classification": "good"},
    {"title": "Tecnologia inovadora ajuda a monitorar e prevenir queimadas", "classification": "good"},
    {"title": "Programa de educação ambiental alcança comunidades rurais e urbanas", "classification": "good"},
    {"title": "Iniciativas locais promovem uso sustentável da água e dos recursos naturais", "classification": "good"},
    {"title": "Adoção de agricultura orgânica reduz impacto ambiental e promove saúde", "classification": "good"},
    {"title": "Crescimento de áreas verdes urbanas melhora qualidade de vida da população", "classification": "good"},
    {"title": "Reciclagem de resíduos sólidos diminui quantidade de lixo em aterros", "classification": "good"},
    {"title": "Gestão eficiente de resíduos industriais minimiza impacto ambiental", "classification": "good"},
    {"title": "Conservação de ecossistemas marinhos protege espécies marinhas ameaçadas", "classification": "good"},
    {"title": "Adoção de transporte público e sustentável reduz emissões de gases poluentes", "classification": "good"},
    {"title": "Projetos de recuperação de nascentes garantem abastecimento de água de qualidade", "classification": "good"},
    {"title": "Uso de energias renováveis torna comunidades autossuficientes e sustentáveis", "classification": "good"},
    {"title": "Engajamento da sociedade civil fortalece proteção ambiental e conservação", "classification": "good"},
    {"title": "Investimentos em pesquisa científica resultam em soluções para desafios ambientais", "classification": "good"},
    {"title": "Ações de preservação de oceanos garantem pesca sustentável e biodiversidade", "classification": "good"},
    {"title": "Educação ambiental nas escolas forma cidadãos conscientes e responsáveis", "classification": "good"},
    {"title": "Parcerias entre setor público e privado promovem inovações sustentáveis", "classification": "good"},
    {"title": "Iniciativas de reflorestamento aumentam cobertura vegetal e combatem erosão", "classification": "good"},
    {"title": "Programas de conservação de água garantem uso sustentável e eficiente", "classification": "good"},
    {"title": "Restauração de áreas degradadas revitaliza paisagens e ecossistemas", "classification": "good"},
    {"title": "Gestão ambiental em empresas reduz impacto e promove responsabilidade social", "classification": "good"},
    {"title": "Preservação de habitats naturais garante equilíbrio ecológico e biodiversidade", "classification": "good"},
    {"title": "Agricultura familiar adota práticas sustentáveis e fortalece economias locais", "classification": "good"},
    {"title": "Inovações tecnológicas promovem desenvolvimento sustentável e soluções verdes", "classification": "good"},
    {"title": "Recuperação de áreas contaminadas revitaliza ecossistemas e protege saúde humana", "classification": "good"},
    {"title": "Participação da juventude em ações ambientais garante futuro sustentável", "classification": "good"},
    {"title": "Queimadas destroem área de preservação ecológica, causando perda irreparável", "classification": "bad"},
    {"title": "Chuvas torrenciais provocam deslizamentos e deixam comunidades isoladas", "classification": "bad"},
    {"title": "Enchentes repentinas causam danos em infraestrutura urbana e afetam moradores", "classification": "bad"},
    {"title": "Assoreamento de rios compromete fauna e flora aquática, gerando desequilíbrio", "classification": "bad"},
    {"title": "Barragem apresenta rachaduras e risco iminente de rompimento", "classification": "bad"},
    {"title": "Deslizamentos em encostas ameaçam residências e causam desalojamento", "classification": "bad"},
    {"title": "Poluição do ar atinge índices alarmantes e prejudica saúde da população", "classification": "bad"},
    {"title": "Aquecimento global intensifica fenômenos climáticos extremos, aumentando danos", "classification": "bad"},
    {"title": "Mudanças climáticas causam escassez de água e conflitos por recursos", "classification": "bad"},
    {"title": "Incêndio florestal destrói habitats e causa extinção de espécies vulneráveis", "classification": "bad"},
    {"title": "Deslizamento de terra em área urbana causa vítimas e destruição", "classification": "bad"},
    {"title": "Poluição industrial contamina solo e águas subterrâneas, prejudicando saúde", "classification": "bad"},
    {"title": "Aquecimento global ameaça derretimento de calotas polares, elevando o nível do mar", "classification": "bad"},
    {"title": "Mudanças climáticas afetam produção agrícola e geram fome em regiões vulneráveis", "classification": "bad"},
    {"title": "Desmatamento ilegal destrói habitats de espécies e aumenta erosão do solo", "classification": "bad"},
    {"title": "Poluição sonora em áreas urbanas impacta saúde mental e bem-estar da população", "classification": "bad"},
    {"title": "Aquecimento global aumenta ocorrência de doenças infecciosas e epidemias", "classification": "bad"},
    {"title": "Mudanças climáticas causam migrações forçadas e conflitos por território", "classification": "bad"},
    {"title": "Incêndios em áreas naturais provocam perda de biodiversidade e destruição", "classification": "bad"},
    {"title": "Deslizamento de terra em encosta destrói plantações e impacta economia local", "classification": "bad"},
    {"title": "Queimadas descontroladas causam fumaça tóxica e problemas respiratórios", "classification": "bad"},
    {"title": "Chuvas intensas causam alagamentos e colapso de sistemas de drenagem", "classification": "bad"},
    {"title": "Enchentes repentinas destroem lavouras e prejudicam agricultura familiar", "classification": "bad"},
    {"title": "Assoreamento de lagos e represas reduz disponibilidade de água potável", "classification": "bad"},
    {"title": "Barragem em estado crítico ameaça vida de comunidades ribeirinhas", "classification": "bad"},
    {"title": "Deslizamentos de encostas causam bloqueio de estradas e isolamento de vilarejos", "classification": "bad"},
    {"title": "Poluição do ar em áreas industriais impacta saúde de trabalhadores e moradores", "classification": "bad"},
    {"title": "Aquecimento global causa acidificação dos oceanos, prejudicando vida marinha", "classification": "bad"},
    {"title": "Mudanças climáticas geram eventos climáticos extremos e desastres naturais", "classification": "bad"},
	{"title": "Recuperação de área degradada restaura habitat de espécies ameaçadas", "classification": "good"},
    {"title": "Projeto de educação ambiental sensibiliza comunidades e reduz desperdício", "classification": "good"},
    {"title": "Campanha de reciclagem conscientiza população e diminui poluição", "classification": "good"},
    {"title": "Conservação de áreas protegidas preserva biodiversidade e ecossistemas", "classification": "good"},
    {"title": "Adoção de energia solar reduz emissões de carbono e promove sustentabilidade", "classification": "good"},
    {"title": "Inovações tecnológicas auxiliam no monitoramento e prevenção de queimadas", "classification": "good"},
    {"title": "Programa de reflorestamento revitaliza áreas degradadas e absorve CO2", "classification": "good"},
    {"title": "Iniciativas locais promovem uso sustentável de recursos e preservação", "classification": "good"},
    {"title": "Adoção de práticas agrícolas sustentáveis aumenta produtividade e conserva solo", "classification": "good"},
    {"title": "Criação de parques urbanos melhora qualidade de vida e promove bem-estar", "classification": "good"},
    {"title": "Coleta seletiva e reciclagem reduzem impacto ambiental e promovem economia", "classification": "good"},
    {"title": "Gestão eficiente de resíduos industriais reduz poluição e preserva recursos", "classification": "good"},
    {"title": "Preservação de oceanos garante pesca sustentável e conservação marinha", "classification": "good"},
    {"title": "Uso de transporte público e bicicletas diminui emissões de CO2 e congestionamento", "classification": "good"},
    {"title": "Recuperação de nascentes e mananciais garante abastecimento de água potável", "classification": "good"},
    {"title": "Energias renováveis como eólica e hidrelétrica contribuem para matriz limpa", "classification": "good"},
    {"title": "Participação da comunidade em ações ambientais fortalece conscientização e cuidado", "classification": "good"},
    {"title": "Investimentos em pesquisa e desenvolvimento geram soluções sustentáveis", "classification": "good"},
    {"title": "Conservação de florestas tropicais protege biodiversidade e regula clima global", "classification": "good"},
    {"title": "Educação ambiental em escolas forma cidadãos conscientes e responsáveis", "classification": "good"},
    {"title": "Parcerias público-privadas incentivam inovações verdes e eficiência energética", "classification": "good"},
    {"title": "Reflorestamento de áreas degradadas reduz erosão e protege solos férteis", "classification": "good"},
    {"title": "Programas de reuso de água garantem sustentabilidade hídrica e economia", "classification": "good"},
    {"title": "Restauração de ecossistemas marinhos promove turismo sustentável e conservação", "classification": "good"},
    {"title": "Gestão ambiental em empresas reduz impacto e promove responsabilidade social", "classification": "good"},
    {"title": "Preservação de habitats naturais garante equilíbrio ecológico e biodiversidade", "classification": "good"},
    {"title": "Agricultura familiar adota práticas sustentáveis e fortalece economias locais", "classification": "good"},
    {"title": "Inovações tecnológicas promovem desenvolvimento sustentável e soluções verdes", "classification": "good"},
    {"title": "Recuperação de áreas contaminadas revitaliza ecossistemas e protege saúde humana", "classification": "good"},
    {"title": "Participação da juventude em ações ambientais garante futuro sustentável", "classification": "good"},
	{"title": "Queimadas criminosas destroem vasta área de floresta amazônica", "classification": "bad"},
    {"title": "Chuvas torrenciais causam enchentes e deixam centenas de desabrigados", "classification": "bad"},
    {"title": "Enchentes repentinas destroem plantações e afetam agricultura familiar", "classification": "bad"},
    {"title": "Assoreamento de rio compromete abastecimento de água de cidade inteira", "classification": "bad"},
    {"title": "Barragem se rompe e lança rejeitos tóxicos em curso d'água, contaminando", "classification": "bad"},
    {"title": "Deslizamentos em encostas destroem moradias e causam mortes", "classification": "bad"},
    {"title": "Poluição do ar atinge níveis alarmantes e causa aumento de doenças respiratórias", "classification": "bad"},
    {"title": "Aquecimento global intensifica furacões e tempestades, causando danos", "classification": "bad"},
    {"title": "Mudanças climáticas causam escassez de água e conflitos por recursos hídricos", "classification": "bad"},
    {"title": "Incêndio florestal de grande proporção destrói ecossistema único", "classification": "bad"},
    {"title": "Deslizamento de terra em área urbana causa colapso de prédios e infraestrutura", "classification": "bad"},
    {"title": "Poluição industrial contamina lençóis freáticos e prejudica saúde da população", "classification": "bad"},
    {"title": "Aquecimento global derrete geleiras e eleva nível dos oceanos, ameaçando cidades costeiras", "classification": "bad"},
    {"title": "Mudanças climáticas geram secas prolongadas e perda de safra agrícola", "classification": "bad"},
    {"title": "Desmatamento ilegal destrói habitat de animais silvestres e aumenta caça ilegal", "classification": "bad"},
    {"title": "Poluição sonora em áreas urbanas causa estresse e problemas de saúde mental", "classification": "bad"},
    {"title": "Aquecimento global aumenta proliferação de doenças transmitidas por mosquitos", "classification": "bad"},
    {"title": "Mudanças climáticas causam deslocamento de populações e refugiados ambientais", "classification": "bad"},
    {"title": "Incêndios em áreas de preservação ameaçam extinção de espécies endêmicas", "classification": "bad"},
    {"title": "Deslizamento de terra em área agrícola causa perda milionária para agricultores", "classification": "bad"},
    {"title": "Queimadas descontroladas geram fumaça tóxica e prejudicam saúde pública", "classification": "bad"},
    {"title": "Chuvas intensas causam erosão do solo e destruição de estradas rurais", "classification": "bad"},
    {"title": "Enchentes repentinas destroem reservatórios de água e afetam abastecimento", "classification": "bad"},
    {"title": "Assoreamento de lagos reduz biodiversidade aquática e impacta pesca", "classification": "bad"},
    {"title": "Barragem em estado crítico eleva risco de desastre ambiental e evacuações", "classification": "bad"},
    {"title": "Deslizamentos de encostas bloqueiam vias de acesso e isolam comunidades", "classification": "bad"},
    {"title": "Poluição do ar em regiões metropolitanas causa doenças respiratórias em crianças", "classification": "bad"},
    {"title": "Aquecimento global acidifica oceanos e prejudica vida marinha, especialmente corais", "classification": "bad"},
    {"title": "Mudanças climáticas intensificam tempestades e aumentam risco de desastres", "classification": "bad"},
    {"title": "Incêndios florestais em áreas de conservação ameaçam patrimônio natural", "classification": "bad"},
    {"title": "Queimadas em florestas tropicais destroem diversidade genética de espécies", "classification": "bad"},
    {"title": "Chuvas torrenciais causam alagamentos em áreas urbanas e prejuízos materiais", "classification": "bad"},
    {"title": "Enchentes repentinas afetam plantações e provocam escassez de alimentos", "classification": "bad"},
    {"title": "Assoreamento de rios compromete ecossistema aquático e afeta pesca", "classification": "bad"},
	{"title": "Recuperação de área degradada revitaliza ecossistema e reintroduz espécies nativas", "classification": "good"},
    {"title": "Projeto de conscientização ambiental reduz consumo de plásticos e lixo marinho", "classification": "good"},
    {"title": "Campanha de reciclagem aumenta taxa de reciclagem e diminui poluição", "classification": "good"},
    {"title": "Conservação de áreas protegidas preserva paisagens naturais e promove turismo sustentável", "classification": "good"},
    {"title": "Adoção de energia renovável reduz emissões de gases de efeito estufa e promove energia limpa", "classification": "good"},
    {"title": "Tecnologia de monitoramento por drones ajuda a detectar e combater queimadas", "classification": "good"},
    {"title": "Programa de reflorestamento recupera biodiversidade e aumenta cobertura vegetal", "classification": "good"},
    {"title": "Iniciativas locais promovem uso sustentável de recursos naturais e preservação ambiental", "classification": "good"},
    {"title": "Adoção de práticas agrícolas sustentáveis melhora qualidade do solo e aumenta produtividade", "classification": "good"},
    {"title": "Criação de parques urbanos reduz ilhas de calor e promove lazer e bem-estar", "classification": "good"},
    {"title": "Programa de coleta seletiva e reciclagem reduz quantidade de resíduos e promove economia circular", "classification": "good"},
    {"title": "Gestão eficiente de resíduos industriais minimiza impacto ambiental e riscos à saúde", "classification": "good"},
    {"title": "Preservação de oceanos protege espécies marinhas e garante pesca sustentável", "classification": "good"},
    {"title": "Uso de transporte público e ciclovias reduz emissões de gases poluentes e congestionamentos", "classification": "good"},
    {"title": "Recuperação de nascentes e mananciais garante abastecimento de água de qualidade", "classification": "good"},
    {"title": "Investimentos em energias renováveis promovem autonomia energética e desenvolvimento sustentável", "classification": "good"},
    {"title": "Participação da comunidade em projetos ambientais fortalece engajamento e responsabilidade ambiental", "classification": "good"},
    {"title": "Inovações tecnológicas sustentáveis geram empregos verdes e estimulam economia circular", "classification": "good"},
    {"title": "Conservação de florestas tropicais regula clima global e preserva biodiversidade", "classification": "good"},
    {"title": "Educação ambiental nas escolas forma cidadãos conscientes e agentes de mudança", "classification": "good"},
    {"title": "Parcerias público-privadas promovem soluções sustentáveis e inovações verdes", "classification": "good"},
    {"title": "Reflorestamento de áreas degradadas reduz erosão e promove conservação do solo", "classification": "good"},
    {"title": "Programas de reuso de água garantem uso eficiente dos recursos hídricos", "classification": "good"},
    {"title": "Restauração de ecossistemas marinhos preserva biodiversidade e ecossistemas marinhos", "classification": "good"},
    {"title": "Gestão ambiental em empresas promove responsabilidade social e redução de impactos", "classification": "good"},
    {"title": "Preservação de habitats naturais garante equilíbrio ecológico e proteção de espécies", "classification": "good"},
    {"title": "Agricultura familiar adota práticas sustentáveis e contribui para segurança alimentar", "classification": "good"},
    {"title": "Inovações tecnológicas sustentáveis impulsionam desenvolvimento econômico e social", "classification": "good"},
    {"title": "Recuperação de áreas contaminadas revitaliza ecossistemas e promove saúde pública", "classification": "good"},
    {"title": "Participação ativa da juventude em ações ambientais garante futuro sustentável", "classification": "good"},
    {"title": "Projeto de educação ambiental sensibiliza comunidades e estimula ações locais", "classification": "good"},
    {"title": "Campanha de reciclagem aumenta consciência ambiental e reduz desperdício", "classification": "good"},
    {"title": "Conservação de áreas protegidas preserva biodiversidade e mantém ecossistemas", "classification": "good"},
    {"title": "Adoção de energia limpa reduz emissões de CO2 e promove desenvolvimento sustentável", "classification": "good"},
    {"title": "Tecnologia de monitoramento por satélite ajuda a prevenir desmatamento e queimadas", "classification": "good"},
    {"title": "Programa de reflorestamento recupera áreas degradadas e reintroduz espécies nativas", "classification": "good"},
    {"title": "Iniciativas locais promovem uso consciente de recursos e preservação da natureza", "classification": "good"},
    {"title": "Adoção de práticas agrícolas sustentáveis melhora qualidade do solo e aumenta produtividade", "classification": "good"},
    {"title": "Criação de parques urbanos aumenta áreas verdes e promove saúde da população", "classification": "good"},
    {"title": "Programa de reciclagem reduz quantidade de lixo e promove economia circular", "classification": "good"},
	{"title": "Projeto de reflorestamento recupera áreas degradadas e restaura biodiversidade", "classification": "good"},
    {"title": "Iniciativas de reciclagem geram empregos verdes e promovem economia sustentável", "classification": "good"},
    {"title": "Programa de proteção a espécies ameaçadas amplia áreas de conservação e preserva fauna", "classification": "good"},
    {"title": "Investimentos em energias renováveis impulsionam desenvolvimento sustentável e reduzem emissões", "classification": "good"},
    {"title": "Campanhas de conscientização reduzem uso de plásticos e promovem consumo consciente", "classification": "good"},
    {"title": "Tecnologias limpas e sustentáveis diminuem impactos ambientais e melhoram qualidade de vida", "classification": "good"},
    {"title": "Programas de educação ambiental fortalecem cidadania e responsabilidade ecológica", "classification": "good"},
    {"title": "Inovações agrícolas sustentáveis aumentam produtividade e garantem segurança alimentar", "classification": "good"},
    {"title": "Projetos de reuso de água promovem uso eficiente dos recursos hídricos e preservação", "classification": "good"},
    {"title": "Construção de parques e áreas verdes urbanas melhora qualidade de vida e bem-estar", "classification": "good"},
    {"title": "Ações de preservação de oceanos protegem ecossistemas marinhos e espécies marinhas", "classification": "good"},
    {"title": "Adoção de transporte público e ciclovias reduz emissões de carbono e congestionamentos", "classification": "good"},
    {"title": "Programas de recuperação de nascentes garantem abastecimento de água e conservação", "classification": "good"},
    {"title": "Parcerias público-privadas impulsionam soluções sustentáveis e inovações verdes", "classification": "good"},
    {"title": "Gestão eficiente de resíduos industriais minimiza poluição e preserva recursos naturais", "classification": "good"},
    {"title": "Projeto de restauração de ecossistemas marinhos fortalece biodiversidade e proteção costeira", "classification": "good"},
    {"title": "Ações de conscientização reduzem desperdício de alimentos e promovem consumo responsável", "classification": "good"},
    {"title": "Inovações tecnológicas sustentáveis geram empregos verdes e impulsionam economia circular", "classification": "good"},
    {"title": "Preservação de habitats naturais garante equilíbrio ecológico e proteção de espécies", "classification": "good"},
    {"title": "Educação ambiental nas escolas forma cidadãos conscientes e agentes de mudança", "classification": "good"},
    {"title": "Gestão ambiental em empresas promove responsabilidade social e redução de impactos", "classification": "good"},
    {"title": "Parques e reservas naturais garantem conservação de biodiversidade e ecossistemas", "classification": "good"},
    {"title": "Ações de reflorestamento mitigam mudanças climáticas e reduzem riscos de desastres naturais", "classification": "good"},
    {"title": "Programas de coleta seletiva e reciclagem contribuem para economia circular e sustentabilidade", "classification": "good"},
    {"title": "Campanhas de conscientização reduzem poluição do ar e melhoram saúde da população", "classification": "good"},
    {"title": "Uso de energias limpas e renováveis reduz emissões de gases de efeito estufa e promove desenvolvimento sustentável", "classification": "good"},
    {"title": "Preservação de florestas tropicais regula clima global e conserva biodiversidade", "classification": "good"},
    {"title": "Adoção de práticas agrícolas sustentáveis melhora saúde do solo e aumenta produtividade", "classification": "good"},
    {"title": "Iniciativas locais promovem uso consciente de recursos naturais e preservação ambiental", "classification": "good"},
    {"title": "Conscientização sobre consumo responsável reduz impactos ambientais e promove sustentabilidade", "classification": "good"},
    {"title": "Ações de proteção a manguezais preservam ecossistemas costeiros e habitats de espécies", "classification": "good"},
    {"title": "Recuperação de áreas degradadas revitaliza ecossistemas e reintroduz espécies nativas", "classification": "good"},
    {"title": "Projeto de conscientização ambiental reduz consumo de plásticos e lixo marinho", "classification": "good"},
    {"title": "Campanha de reciclagem aumenta taxa de reciclagem e diminui poluição", "classification": "good"},
    {"title": "Conservação de áreas protegidas preserva paisagens naturais e promove turismo sustentável", "classification": "good"},
    {"title": "Adoção de energia renovável reduz emissões de gases de efeito estufa e promove energia limpa", "classification": "good"},
    {"title": "Tecnologia de monitoramento por drones ajuda a detectar e combater queimadas", "classification": "good"},
    {"title": "Programa de reflorestamento recupera biodiversidade e aumenta cobertura vegetal", "classification": "good"},
    {"title": "Iniciativas locais promovem uso sustentável de recursos naturais e preservação ambiental", "classification": "good"},
     {"title": "Nova tecnologia de reciclagem transforma plásticos em materiais de construção sustentáveis", "classification": "good"},
    {"title": "Desenvolvimento de bioplásticos reduz impacto ambiental de embalagens descartáveis", "classification": "good"},
    {"title": "Projeto de reflorestamento cria corredores verdes e conecta habitats de espécies ameaçadas", "classification": "good"},
    {"title": "Uso de energias renováveis em indústrias reduz emissões de gases de efeito estufa", "classification": "good"},
    {"title": "Recuperação de áreas degradadas promove regeneração natural e aumento da biodiversidade", "classification": "good"},
    {"title": "Programa de educação ambiental conscientiza comunidades sobre conservação dos recursos naturais", "classification": "good"},
    {"title": "Adoção de práticas agrícolas sustentáveis melhora qualidade do solo e aumenta produtividade", "classification": "good"},
    {"title": "Investimentos em pesquisa de energias limpas impulsionam avanços tecnológicos", "classification": "good"},
    {"title": "Conservação de áreas marinhas protege ecossistemas costeiros e espécies marinhas", "classification": "good"},
    {"title": "Plano de manejo florestal sustentável garante uso responsável dos recursos madeireiros", "classification": "good"},
    {"title": "Projeto de recuperação de nascentes revitaliza cursos d'água e aumenta disponibilidade hídrica", "classification": "good"},
    {"title": "Campanha de conscientização reduz descarte de resíduos plásticos em oceanos", "classification": "good"},
    {"title": "Implementação de sistemas de transporte público eficientes reduz emissões de CO2", "classification": "good"},
    {"title": "Restauração de ecossistemas costeiros protege contra erosão e eventos climáticos extremos", "classification": "good"},
    {"title": "Adoção de práticas de pesca sustentável preserva estoques pesqueiros e ecossistemas marinhos", "classification": "good"},
    {"title": "Gestão eficiente de resíduos sólidos reduz impactos ambientais e promove economia circular", "classification": "good"},
    {"title": "Investimentos em energia solar descentralizada levam eletricidade a comunidades remotas", "classification": "good"},
    {"title": "Programa de proteção de espécies ameaçadas reintroduz animais em seus habitats naturais", "classification": "good"},
    {"title": "Desenvolvimento de tecnologias de dessalinização amplia acesso à água potável em regiões áridas", "classification": "good"},
    {"title": "Reciclagem de resíduos eletrônicos reduz impacto ambiental e recupera materiais preciosos", "classification": "good"},
    {"title": "Incentivos fiscais para empresas sustentáveis estimulam práticas ambientalmente responsáveis", "classification": "good"},
    {"title": "Preservação de áreas de recarga hídrica garante abastecimento de água para comunidades locais", "classification": "good"},
    {"title": "Uso de biodiversidade nativa em paisagismo urbano promove ecossistemas resilientes", "classification": "good"},
    {"title": "Inovações em agricultura de precisão reduzem desperdício de recursos e aumentam produtividade", "classification": "good"},
    {"title": "Campanha de conscientização sobre conservação de florestas reduz desmatamento ilegal", "classification": "good"},
    {"title": "Adoção de sistemas de irrigação eficientes reduz consumo de água na agricultura", "classification": "good"},
    {"title": "Restauração de áreas de manguezais protege contra tempestades e preserva biodiversidade", "classification": "good"},
    {"title": "Programa de voluntariado ambiental engaja comunidades em ações de conservação", "classification": "good"},
    {"title": "Desenvolvimento de veículos elétricos reduz emissões de poluentes e dependência de combustíveis fósseis", "classification": "good"},
    {"title": "Recuperação de áreas degradadas por mineração promove reabilitação ambiental e social", "classification": "good"},
    {"title": "Incentivos para construções sustentáveis reduzem consumo de recursos naturais e desperdício", "classification": "good"},
    {"title": "Restauração de áreas de restinga preserva ecossistemas costeiros e biodiversidade", "classification": "good"},
    {"title": "Programa de recuperação de solos degradados aumenta capacidade produtiva de áreas agrícolas", "classification": "good"},
    {"title": "Monitoramento por satélite melhora fiscalização de desmatamento e queimadas ilegais", "classification": "good"},
    {"title": "Iniciativas de turismo sustentável promovem conservação de áreas naturais e culturais", "classification": "good"},
    {"title": "Adoção de políticas de conservação de água em indústrias reduz consumo e desperdício", "classification": "good"},
    {"title": "Restauração de áreas degradadas por erosão evita perdas de solo e conserva recursos", "classification": "good"},
    {"title": "Programas de educação ambiental em escolas formam jovens conscientes e engajados", "classification": "good"},
    {"title": "Desenvolvimento de tecnologias de captura de CO2 contribui para combate às mudanças climáticas", "classification": "good"},
]

# Salvar os dados em um arquivo JSON
with open('dados_noticias.json', 'w') as arquivo:
    json.dump(dados, arquivo)

print("Arquivo JSON criado com sucesso.")
